"""search query table added

Revision ID: 14ac930aa98f
Revises: dde311c708e7
Create Date: 2022-09-22 22:08:19.304728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ac930aa98f'
down_revision = 'dde311c708e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_query_time_created'), 'search_query', ['time_created'], unique=False)
    op.drop_column('user', 'search_plot')
    op.drop_column('user', 'time_created')
    op.drop_column('user', 'time_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_updated', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('time_created', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('user', sa.Column('search_plot', sa.VARCHAR(length=120), nullable=True))
    op.drop_index(op.f('ix_search_query_time_created'), table_name='search_query')
    op.drop_table('search_query')
    # ### end Alembic commands ###
